BEGIN TRANSACTION;
CREATE TABLE 'CDs' ('id_cd' INTEGER PRIMARY KEY  NOT NULL ,'id_artista' INTEGER,'nombre' TEXT,'anio' INTEGER,'canciones' TEXT,'thumbnail' TEXT, 'imagenes' TEXT,'link' TEXT, 'visitas' INTEGER, 'megusta' INTEGER);
CREATE TABLE 'artista_tag' ('id_artista' INTEGER NOT NULL , 'id_tag' INTEGER NOT NULL );
CREATE TABLE 'artistas' ('id_artista' INTEGER PRIMARY KEY  NOT NULL , 'nombre' TEXT NOT NULL , 'id_genero' INTEGER NOT NULL , 'nacionalidad' TEXT, 'banda' TEXT, 'imagenes' TEXT, 'link' TEXT, 'visitas' INTEGER, 'megusta' INTEGER);
CREATE TABLE 'cd_tag' ('id_cd' INTEGER NOT NULL , 'id_tag' INTEGER NOT NULL );
CREATE TABLE 'generos' ('id_genero' INTEGER PRIMARY KEY  NOT NULL , 'nombre' TEXT NOT NULL );
CREATE TABLE 'tags' ('id_tag' INTEGER PRIMARY KEY  NOT NULL , 'nombre' TEXT NOT NULL );
CREATE TABLE 'usuarios' ('id_user' INTEGER PRIMARY KEY  NOT NULL , 'user' TEXT, 'pass' TEXT);
INSERT INTO usuarios VALUES(1,'admin','21232f297a57a5a743894a0e4a801fc3');
INSERT INTO usuarios VALUES(2,'lolo',',bmn');
COMMIT;
