
DROP TABLE IF EXISTS 'CDs';
CREATE TABLE 'CDs' ('id_cd' INTEGER PRIMARY KEY  NOT NULL ,'id_artista' INTEGER,'nombre' TEXT,'anio' INTEGER,'canciones' TEXT,'thumbnail' TEXT, 'imagenes' TEXT,'link' TEXT, 'visitas' INTEGER, 'megusta' INTEGER);
DROP TABLE IF EXISTS 'artistas';
CREATE TABLE 'artistas' ('id_artista' INTEGER PRIMARY KEY  NOT NULL , 'nombre' TEXT NOT NULL , 'id_genero' INTEGER NOT NULL , 'nacionalidad' TEXT, 'banda' TEXT, 'imagenes' TEXT, 'link' TEXT, 'visitas' INTEGER, 'megusta' INTEGER);
DROP TABLE IF EXISTS 'generos';
CREATE TABLE 'generos' ('id_genero' INTEGER PRIMARY KEY  NOT NULL , 'nombre' TEXT NOT NULL );
DROP TABLE IF EXISTS 'tags';
CREATE TABLE 'tags' ('id_tag' INTEGER PRIMARY KEY  NOT NULL , 'nombre' TEXT NOT NULL );
DROP TABLE IF EXISTS 'artista_tag';
CREATE TABLE 'artista_tag' ('id_artista' INTEGER NOT NULL , 'id_tag' INTEGER NOT NULL );
DROP TABLE IF EXISTS 'cd_tag';
CREATE TABLE 'cd_tag' ('id_cd' INTEGER NOT NULL , 'id_tag' INTEGER NOT NULL );
DROP TABLE IF EXISTS 'usuarios';
CREATE TABLE 'usuarios' ('id_user' INTEGER PRIMARY KEY  NOT NULL , 'user' TEXT, 'pass' TEXT);

INSERT INTO 'usuarios' VALUES(1,'admin','21232f297a57a5a743894a0e4a801fc3');

INSERT INTO 'generos' VALUES(1,'Rock nacional');
INSERT INTO 'generos' VALUES(2,'Rock internacional');
INSERT INTO 'generos' VALUES(3,'Folklore');
INSERT INTO 'generos' VALUES(4,'Pop');
INSERT INTO 'generos' VALUES(5,'Tango');
INSERT INTO 'generos' VALUES(6,'Reggae');

INSERT INTO 'artistas' VALUES(1,'Encias Sangrantes',1,'Argentina','Alequio: teclado y coros\nGaby: bateria\nGordo Pablo: percusion y coros\nJuan Cruz: voz y bajo\nToto: voz y guitarra\nZoty: malodion y armonica','http://www.rock.com.ar/img/foto/3/3450.jpg','http://www.enciassangrantes.com.ar/',0,0);
INSERT INTO 'artistas' VALUES(2,'La Vela Puerca',1,'Uruguay','Alejandro Picone: trompeta\nCarlos Quijano: saxo tenor\nNicolás Lieutier: bajo\nPepe Canedo: batería\nRafael Dibello: guitarra\nSantiago Butler: guitarra\nSebastián Cebreiro: voz\nSebastián Teysera: voz\n','http://www.rock.com.ar/img/foto/1/1973.jpg','http://www.velapuerca.com/',0,0);
INSERT INTO 'artistas' VALUES(3,'Savoretti & los Indescriptibles',1,'Argentina','Diego Savoretti: Pianos, Guitarras y Voz.\nHernan Crosina: Bajo.\nLisandro Gabbarini: Bateria.\nVictor Fillipich: Guitarra, Teclados y Coros.\nAgustin Guarco: Guitarra y Coros','public_html/img/bandas/3/savore.jpg','http://www.myspace.com/savorettiylosindescriptibles',0,0);
INSERT INTO 'artistas' VALUES(4,'Manu Chao',2,'Francia','Radio Bemba [1987-1994]\nSolista [actualidad]','link','link',0,0);

INSERT INTO 'CDs' VALUES(1,1,'Encias Sangrantes',2005,'<ol><li>Tranky panky</li><li>Felicidad</li><li>Babilonia</li><li>La cosecha</li><li>Copate</li><li>Contento</li><li>La tormenta</li><li>Moca namo</li><li>Un poco mas</li><li>Jugo de paty</li><li>Campeon</li></ol>','http://www.rock.com.ar/img/foto/disco/7/7473.jpg','http://www.enciassangrantes.com.ar/disco1.png','http://www.enciassangrantes.com.ar/Encias%20Sangrantes.rar',0,0);
INSERT INTO 'CDs' VALUES(2,1,'Vehemencia',2009,'<ol><li>Rebozado</li><li>Oye Bien</li><li>Hasta</li><li>El Pozo</li><li>Keme Kemo</li><li>Agua</li><li>Santa Catalina</li><li>Viajero</li><li>Vuelo</li><li>Flores</li><li>Isabel</li></ol>','http://www.enciassangrantes.com.ar/disco2.png','http://a4.ec-images.myspacecdn.com/images02/113/c39039865d6a4647809f6a5f473e66e9/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/123/5d77cb508441492bb77e396557e5edd9/l.jpg','http://www.enciassangrantes.com.ar/Encias%20sangrantes%20-%20Vehemencia.rar',0,0);
INSERT INTO 'CDs' VALUES(3,2,'Deskarado',1999,'<ol><li>Alta magia</li><li>El bandido Saltodemata</li><li>Común Cangrejo</li><li>Madre Resistencia</li><li>Pedro</li><li>Paren hoy</li><li>Vuelan palos</li><li>Mi semilla</li><li>A su bola</li><li>Gente</li><li>De tal palo, tal astilla</li><li>El Gavilán</li><li>Las polillas</li></ol>','http://www.rock.com.ar/img/foto/disco/4/4124.jpg','http://www.genesisdiscos.com.ar/images/La_Vela_Puerca-La_Vela_Puerca.jpg|-|http://www.fechasdebandas.com.ar/files/files/lavela.jpg|-|http://www.rock.com.ar/blog/media/2009/12/foto16.jpg|-|http://www.noticiasmercedinas.com/la-vela-puerca-1.jpg|-|http://www.rock.com.ar/img/foto/2/2289.jpg','http://www.velapuerca.com/discos/la_vela_puerca_deskarado/',0,0);
INSERT INTO 'CDs' VALUES(4,2,'De bichos y flores',2001,'<ol><li>Por la ciudad</li><li>Por dentro </li><li>El viejo </li><li>El huracán </li><li>Contradecir </li><li>El profeta </li><li>Potosí </li><li>Mañana </li><li>El ojo moro </li><li>José sabía </li><li>Rebuscado </li><li>Burbujas </li><li>De no olvidar </li></ol>','http://www.rock.com.ar/img/foto/disco/4/4123.jpg','http://e.imagehost.org/0779/fre.jpg|-|http://www.fechasdebandas.com.ar/files/files/lavela.jpg|-|http://www.rock.com.ar/blog/media/2009/12/foto16.jpg|-|http://www.noticiasmercedinas.com/la-vela-puerca-1.jpg|-|http://www.rock.com.ar/img/foto/2/2289.jpg','http://www.velapuerca.com/discos/de_bichos_y_flores/',0,0);
INSERT INTO 'CDs' VALUES(5,2,'A contraluz',2004,'<ol><li>Llenos de magia </li><li>Sin palabras </li><li>Dice </li><li>De atar </li><li>Va a escampar </li><li>Escobas </li><li>Clarobscuro </li><li>Zafar </li><li>Caldo precoz </li><li>Haciéndose pasar por luz </li><li>En el limbo </li><li>Un frasco </li><li>Doble filo </li><li>A lo verde  </li></ol>','http://www.rock.com.ar/img/foto/disco/4/4122.jpg','http://1.bp.blogspot.com/_MTPVyO_qhvA/SY7jk9PpA3I/AAAAAAAAAII/czG1IIb4vu4/s400/2004-A+contraluz+F.JPG|-|http://www.fechasdebandas.com.ar/files/files/lavela.jpg|-|http://www.rock.com.ar/blog/media/2009/12/foto16.jpg|-|http://www.noticiasmercedinas.com/la-vela-puerca-1.jpg|-|http://www.rock.com.ar/img/foto/2/2289.jpg','http://www.velapuerca.com/discos/a_contraluz/',0,0);
INSERT INTO 'CDs' VALUES(6,2,'El impulso',2007,'<ol><li>Frágil</li><li>El Señor</li><li>Su ración</li><li>Neutro</li><li>Me pierdo</li><li>Clones</li><li>Colabore</li><li>Para no verme más</li><li>Con el destino</li><li>Sanar</li><li>Pino</li><li>La sin razón</li><li>Hoy tranquilo</li></ol>','http://www.rock.com.ar/img/foto/disco/5/5175.jpg','http://www.velapuerca.com/media/uploads/covers/cd04_01.jpg|-|http://www.fechasdebandas.com.ar/files/files/lavela.jpg|-|http://www.rock.com.ar/blog/media/2009/12/foto16.jpg|-|http://www.noticiasmercedinas.com/la-vela-puerca-1.jpg|-|http://www.rock.com.ar/img/foto/2/2289.jpg','http://www.velapuerca.com/discos/el_impulso/',0,0);
INSERT INTO 'CDs' VALUES(7,2,'Normalmente anormal',2009,'<ol><li>De atar </li><li>Por dentro </li><li>Doble filo </li><li>Haciéndose pasar por luz </li><li>Mañana </li><li>El Señor </li><li>Colabore</li><li>La sin razón </li><li>Mi semilla </li><li>Va a escampar </li><li>El profeta </li><li>Para no verme más </li><li>Zafar </li><li>El viejo  </li><li>Llenos de magia  </li><li>Jose sabía  </li><li>Razón de ser  </li><li>En vela  </li><li>El cantador  </li><li>Caridad  </li><li>Respira  </li></ol>','http://www.rock.com.ar/img/foto/disco/7/7502.jpg','http://www.velapuerca.com/media/uploads/covers/cd05_01.jpg|-|http://www.fechasdebandas.com.ar/files/files/lavela.jpg|-|http://www.rock.com.ar/blog/media/2009/12/foto16.jpg|-|http://www.noticiasmercedinas.com/la-vela-puerca-1.jpg|-|http://www.rock.com.ar/img/foto/2/2289.jpg','http://www.velapuerca.com/discos/normalmente_anormal/',0,0);
INSERT INTO 'CDs' VALUES(8,2,'Piel y hueso',2011,'<ol><li>Sobre la sien </li><li>...Y así vivir </li><li>La teoría </li><li>Tentación </li><li>Sigo creyendo </li><li>Cada palabra </li><li>Se le va </li><li>El borde </li><li>No se sabe por qué </li><li>Polidoro </li><li>Todo el karma </li><li>Se despierta </li><li>Sé adonde quiere ir </li><li>Sólo un paredón </li><li>El buitre </li><li>Hoy </li><li>3 minutos  </li><li>Réquiem por vos </li></ol>','http://www.rock.com.ar/img/foto/disco/8/8743.jpg','http://www.velapuerca.com/media/uploads/covers/cd06.jpg|-|http://www.fechasdebandas.com.ar/files/files/lavela.jpg|-|http://www.rock.com.ar/blog/media/2009/12/foto16.jpg|-|http://www.noticiasmercedinas.com/la-vela-puerca-1.jpg|-|http://www.rock.com.ar/img/foto/2/2289.jpg','http://www.velapuerca.com/discos/piel_y_hueso/',0,0);
INSERT INTO 'CDs' VALUES(9,4,'Clandestino',1998,'<ol><li>Clandestino - 2:26</li><li>Desaparecido - 3:48</li><li>Bongo Bong - 2:52</li><li>Je Ne T Aime Plus 1:50</li><li>Mentira - 4:37</li><li>Lágrimas de Oro - 2:57</li><li>Mama Call - 2:21</li><li>Luna y Sol - 3:06</li><li>Por el Suelo - 2:21</li><li>Welcome to Tijuana - 4:03</li><li>Día Luna... Día Pena - 1:30</li><li>Malegria - 2:51</li><li>La Vie a 2 - 3:04</li><li>Minha Galera - 2:21</li><li>La Despedida - 3:02</li><li>El Viento - 2:38</li></ol>','http://2.bp.blogspot.com/-RgxhhNm8NuY/TorqNC6QN-I/AAAAAAAABBw/FPZR6W-oMH8/s1600/clandestino.jpg','http://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Manu_Chao_Bondy_France_21-06-2008_b_.JPG/250px-Manu_Chao_Bondy_France_21-06-2008_b_.JPG|-|http://www.solesdigital.com.ar/Wallpapers/Manu_Chao_WP.jpg|-|http://images.coveralia.com/autores/fotos/manu-chao4487.jpg','http://es.wikipedia.org/wiki/Clandestino_(%C3%A1lbum)',0,0);
INSERT INTO 'CDs' VALUES(10,4,'Próxima estación: Esperanza',2000,'<ol><li>Merry Blues - 3:36</li><li>Bixo - 1:52</li><li>El Dorado 1997 - 1:29</li><li>Promiscuity - 1:36</li><li>La Primavera - 1:52</li><li>Me Gustas Tú - 4:00</li><li>Denia - 4:39</li><li>Mi Vida - 2:32</li><li>Trapped By Love - 1:54</li><li>Le Rendez Vous - 1:56</li><li>Mr. Bobby - 3:49</li><li>Papito - 2:51</li><li>La Chinita - 1:33</li><li>La Marea - 2:16</li><li>Homens - 3:18</li><li>La Vacaloca - 2:23</li><li>Infinita Tristeza - 3:56</li></ol>','http://upload.wikimedia.org/wikipedia/en/thumb/a/af/Proxima_Estacion_Esperanza.jpg/220px-Proxima_Estacion_Esperanza.jpg','http://ciudadanogaditano.files.wordpress.com/2011/06/manu-chao-proxima-estacion-esperanza-2001.jpg|-|http://www.solesdigital.com.ar/Wallpapers/Manu_Chao_WP.jpg|-|http://images.coveralia.com/autores/fotos/manu-chao4487.jpg','http://es.wikipedia.org/wiki/http://es.wikipedia.org/wiki/Pr%C3%B3xima_estaci%C3%B3n:_Esperanza',0,0);
INSERT INTO 'CDs' VALUES(11,4,'Radio Bemba Sound System',2002,'<ol><li>Intro - 0:51</li><li>Bienvenida a Tijuana - 1:57</li><li>Machine Gun - 2:15</li><li>Por dónde saldrá el sol? - 2:43</li><li>Peligro - 3:11</li><li>Welcome to Tijuana - 2:51</li><li>El viento - 2:43</li><li>Casa Babylon - 2:36</li><li>Por el suelo - 3:56</li><li>Blood and Fire - 2:36</li><li>EZLN...Para tod@s todo... - 1:43</li><li>Mr Bobby - 3:38</li><li>Bongo Bong - 1:06</li><li>Radio Bemba - 0:22</li><li>Que paso qué pasó - 0:55</li><li>Pinocchio (viaggio in groppa al tonno) - 0:47</li><li>Cahi en la trampa - 2:11</li><li>Clandestino - 3:01</li><li>Rumba de Barcelona - 3:33</li><li>La despedida - 4:04</li><li>Mala vida - 2:28</li><li>Radio Bemba - 0:35</li><li>Que paso qué pasó - 1:12</li><li>Pinocchio (viaggio in groppa al tonno) - 0:46</li><li>La primavera - 3:33</li><li>The Monkey - 2:01</li><li>King Kong Five - 2:45</li><li>Minha galera - 3:18</li><li>Promiscuity - 1:43</li></ol>','http://images.coveralia.com/audio/m/Manu_Chao-Radio_Bemba_Sound_System-Frontal.jpg','http://images.coveralia.com/audio/m/Manu_Chao-Radio_Bemba_Sound_System-Frontal.jpg|-|http://www.solesdigital.com.ar/Wallpapers/Manu_Chao_WP.jpg|-|http://images.coveralia.com/autores/fotos/manu-chao4487.jpg','http://es.wikipedia.org/wiki/Radio_Bemba_Sound_System',0,0);
INSERT INTO 'CDs' VALUES(12,4,'Sibérie métait contéee',2005,'<ol><li>Le ptit jardin</li><li>Petite blonde du bld Brune</li><li>La valse à Sale Temps</li><li>Les mille Paillettes</li><li>Il faut manger</li><li>Helno est mort</li><li>Jai besoin de la lune</li><li>Lautomne est làs</li><li>Si loin de toi je to joue</li><li>100 000 remords</li><li>Trop tot trop tard</li><li>Te tromper</li><li>Madame Banquise</li><li>Les rues de lHiver</li><li>Siberie fleuve amour</li><li>Les petites Planètes</li><li>Te souviens tu</li><li>Jai besoin de la lune</li><li>Dans mon jardin</li><li>Merci bonsoir</li><li>Fou de toi</li><li>Les yeux turquoise</li><li>Siberie</li></ol>','http://1.bp.blogspot.com/_myF9lmSth4M/Swrx_KvYO8I/AAAAAAAAACY/LXn9d8_BTHE/s1600/siberie.jpg','http://1.bp.blogspot.com/_myF9lmSth4M/Swrx_KvYO8I/AAAAAAAAACY/LXn9d8_BTHE/s1600/siberie.jpg|-|http://www.solesdigital.com.ar/Wallpapers/Manu_Chao_WP.jpg|-|http://images.coveralia.com/autores/fotos/manu-chao4487.jpg','http://es.wikipedia.org/wiki/Sib%C3%A9rie_m%27%C3%A9tait_cont%C3%A9ee',0,0);
INSERT INTO 'CDs' VALUES(13,4,'La Radiolina',2007,'<ol><li>13 Días</li><li>Tristeza Maleza</li><li>Politik Kills</li><li>Ranin in paradise</li><li>Besoin de la Lune</li><li>El Kitapena</li><li>Me Llaman Calle</li><li>A Cosa</li><li>The Bleedin Clown</li><li>Mundorévès</li><li>El Hoyo</li><li>La Vida Tómbola</li><li>Mala Fama</li><li>Panik Panik</li><li>Otro Mundo</li><li>Piccola Radiolina</li><li>Y Ahora Qué&#160;?</li><li>Mama Cuchara</li><li>Siberia</li><li>Soñe Otro Mundo</li><li>Amalucada Vida</li></ol>','http://2.bp.blogspot.com/-JBTiwT2KTcs/T6DNoJyjo9I/AAAAAAAAB3o/L02eHOKfNJ8/s1600/album-la-radiolina.jpg','http://2.bp.blogspot.com/-JBTiwT2KTcs/T6DNoJyjo9I/AAAAAAAAB3o/L02eHOKfNJ8/s1600/album-la-radiolina.jpg|-|http://www.solesdigital.com.ar/Wallpapers/Manu_Chao_WP.jpg|-|http://images.coveralia.com/autores/fotos/manu-chao4487.jpg','http://es.wikipedia.org/wiki/La_Radiolina',0,0);
INSERT INTO 'CDs' VALUES(14,4,'Baionarena',2009,'<p>CD 1:</p><ol><li>Panik Panik 04:36</li><li>El Hoyo 05:39</li><li>Peligro 04:10</li><li>Casa Babylon 03:25</li><li>Tumba 00:53</li><li>Mr. Bobby 06:25</li><li>La Primavera 08:16</li><li>Radio Bemba 01:01</li><li>Bienvenida A Tijuana 02:10</li><li>El Viento 04:58</li><li>Monkey 02:20</li><li>Clandestino 03:16</li><li>Desaparecido 07:02</li><li>Rumba De Barcelona 05:01</li><li>La Despedida / Mentira 04:25</li></ol><p>CD2:</p><ol><li>Rainin In Paradize 03:55</li><li>A Cosa 03:35</li><li>La Vacaloca 01:41</li><li>Hamburger Fields / Merry Blues 04:48</li><li>Tristeza Maleza 03:46</li><li>Dia Luna Dia Pena 05:05</li><li>Machine Gun 04:23</li><li>Volver, Volver 03:17</li><li>Radio Bemba / Eldorado 1997 02:33</li><li>Mala Vida 03:30</li><li>Sidi Hbibi 03:25</li><li>Radio Bemba 00:36</li><li>Forzando Maquina / Mr. Bobby 07:17</li><li>Me Quedo Contigo (Si Me Das Elegir) 04:48</li><li>La Vida Tombola 06:29</li><li>L hiver Est L? 04:55</li><li>Cr?v La Vie 04:23</li><li>Pinocchio (Viaggio In Groppa Al Tonno) 03:29</li></ol>','http://www.mundomusica.es/wp-content/uploads/2009/10/2009-baionarena-live-manu-chao.jpg','http://www.mundomusica.es/wp-content/uploads/2009/10/2009-baionarena-live-manu-chao.jpg|-|http://www.solesdigital.com.ar/Wallpapers/Manu_Chao_WP.jpg|-|http://images.coveralia.com/autores/fotos/manu-chao4487.jpg','http://es.wikipedia.org/wiki/Baionarena',0,0);
INSERT INTO 'CDs' VALUES(15,3,'El último verano del mundo',2005,'<ol><li>El último verano del mundo</li><li>El valle que no fue</li><li>La máquina del mal</li><li>Postales de nada</li><li>Tatuajes</li><li>Yo vi pasar tu amor</li><li>El secreto</li><li>Cosas que no están</li><li>A tanto abrigo</li><li>Que esperabas de mi</li><li>Inmortal</li><li>La culpa</li><li>Enero de 2002</li></ol>','http://a1.ec-images.myspacecdn.com/images01/112/51511b93cb6016e94e88fb14ad88e7b2/l.jpg','http://a1.ec-images.myspacecdn.com/images01/112/51511b93cb6016e94e88fb14ad88e7b2/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/17/4a809207334c4ad088892d2477af6b7d/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/17/4a809207334c4ad088892d2477af6b7d/l.jpg','http://bit.ly/GUdX8M ',0,0);
INSERT INTO 'CDs' VALUES(16,3,'Ni siquiera lo intentes',2007,'<ol><li>Discos de Serrat<li>Mariposa de estación</li><li>Lo que no perdí</li><li>Tu voz en off</li><li>Perdón</li><li>El dogo argentino</li><li>Epidemia</li><li>Tu forma de matarme</li><li>Antes de desconocerme</li><li>Nena nena</li><li>Cada cosa al sonar</li><li>El último abandono</li><li>Herida</li><li>Fantasma de tu olor</li><li>La vida que elegiste</li><li>Condenado al éxito</li><li>Vos también</li><li>Voy con vos</li><li>Más que a las arañas</li><li>El día que perdí la cuenta</li><li>Quiero todo</li><li>Chernobil</li><li>Cuando yo era el puente</li><li>Instrumental</li><li>Hombre loop</li><li>Muerte al jazz</li><li>Ni siquiera lo intentes</li><li>La guerra que pasa</li><li>La voz del fondo del mar</li><li>Noches largas</li></ol>','http://a2.ec-images.myspacecdn.com/images01/53/3911669bb7e18b8112260145d7ee3ec3/l.jpg','http://a2.ec-images.myspacecdn.com/images01/53/3911669bb7e18b8112260145d7ee3ec3/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/17/4a809207334c4ad088892d2477af6b7d/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/17/4a809207334c4ad088892d2477af6b7d/l.jpg','www.mixpod.com/savoretti',0,0);
INSERT INTO 'CDs' VALUES(17,3,'Andá a laburar',2009,'<ol><li> NO VINE AL MUNDO A CAMBIARLO</li><li>ME HACES FELIZ</li><li>GRANDES DISEÑOS</li><li>LOS LABIOS DEL PECADO</li><li>POR NADA</li><li>LA BORICUA</li><li>MIENTRAS BUSCABAS</li><li>MIS OTRAS VIDAS</li><li>TORERO</li><li>FOTOS SAGRADAS</li><li>MI AMOR AL ARTE</li><li>COSAS MUY CURIOSAS</li></ol>','http://a2.ec-images.myspacecdn.com/images02/120/e9df604ee79c46f9a9a6dd2fcecfc57e/l.jpg','http://a2.ec-images.myspacecdn.com/images02/120/e9df604ee79c46f9a9a6dd2fcecfc57e/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/17/4a809207334c4ad088892d2477af6b7d/l.jpg|-|http://a2.ec-images.myspacecdn.com/images02/17/4a809207334c4ad088892d2477af6b7d/l.jpg',' http://bit.ly/nqXb3C',0,0);


INSERT INTO 'tags' VALUES(1,'rock');
INSERT INTO 'tags' VALUES(2,'nacional');
INSERT INTO 'tags' VALUES(3,'simpatico');
INSERT INTO 'tags' VALUES(4,'bahiablanca');
INSERT INTO 'tags' VALUES(5,'ska');
INSERT INTO 'tags' VALUES(6,'isabel');
INSERT INTO 'tags' VALUES(7,'frances');
INSERT INTO 'tags' VALUES(8,'murga');

INSERT INTO 'artista_tag' VALUES(1,3);
INSERT INTO 'artista_tag' VALUES(3,4);
INSERT INTO 'artista_tag' VALUES(2,5);
INSERT INTO 'artista_tag' VALUES(1,5);

INSERT INTO 'cd_tag' VALUES(1,1);
INSERT INTO 'cd_tag' VALUES(1,2);
INSERT INTO 'cd_tag' VALUES(1,3);
INSERT INTO 'cd_tag' VALUES(2,6);
INSERT INTO 'cd_tag' VALUES(12,7);
INSERT INTO 'cd_tag' VALUES(3,5);
INSERT INTO 'cd_tag' VALUES(4,5);
INSERT INTO 'cd_tag' VALUES(4,8);
INSERT INTO 'cd_tag' VALUES(15,4);
INSERT INTO 'cd_tag' VALUES(16,4);
INSERT INTO 'cd_tag' VALUES(17,4);
